### PR TITLE
Vanilla js example

### PR DESCRIPTION
**Pull request by sesamechicken**
Perhaps an example without jquery dependancy?

### CODE REVIEW

**Comment by LukyVj** [comment]
Good idea, but it would be better with a redirection or a fullpage iframe instead of a 150/150px iframe :)

**Comment by sesamechicken** [comment]
See line #5
`bullgit.className = "bullgit";`
Add your css there, not inline.

**Comment by LukyVj** [comment]
Oh okay, I've seen a width=150; height=150; 
I thought you wanted to force the iframe size to 150/150

**Comment by dervondenbergen** [comment]
looks like this issue took some time 😂

**Pull request closed without merging**
